### ISSUE TITLE
Screenshot for element?

### ISSUE THREAD

**Issue by MaxAndolini** [daijro/hrequests#10]
I think screenshots should be taken for specific elements instead of the entire page and used in memory without saving.

Like this;

```
image_element = page.find('#captchaframe')
image = image_element.screenshot()
```

**Comment by daijro** [comment]
Fixed in [v0.7.1](https://github.com/daijro/hrequests/commit/b75898c211d4ffdf71f31b643ee94e8f59ed6ae6)
