### ISSUE TITLE
[Update] Update to fit to Botright v0.3

### ISSUE THREAD

**Issue by Vinyzu** [daijro/hrequests#12]
Botright [v0.3](https://github.com/Vinyzu/Botright/commit/1e99b363e9d812941eb4cc1fee964403baddf4b9) released today, you can update the playwright_mock.
Especially the [Mouse Movement](https://github.com/Vinyzu/Botright/blob/main/botright/modules/playwright_mock/mouse.py#L32) is noticeably improved.

**Comment by daijro** [comment]
Thank you so much! I'll add it to my roadmap. I'm currently sick, but I'll get started on this asap ❤️

**Comment by daijro** [comment]
Added in v0.8.0-beta. Should be rolled out with the next release. 👍
