### ISSUE TITLE
allow_redirects parameter does not work as expected

### ISSUE THREAD

**Issue by fmarasoglou** [daijro/hrequests#2]
allow_redirects is supposedly set as True by default, however it appears by default it is set to False.
Even when I enable it I see a strange behavior, where the redirects are not properly followed

**Comment by daijro** [comment]
Hello,

I was not able to reproduce a case where `allow_redirects` is set to False by default; however, I have fixed the strange behavior when following relative redirects.

This should work as intended now:

```py
>>> resp = hrequests.get('http://httpbin.org/redirect/2', history=True)
>>> resp
<Response [200]>
>>> resp.history
[<Response [302]>, <Response [302]>]
```

**Comment by fmarasoglou** [comment]
Hi daijro,
Can you also push the new version to pypi?

**Comment by daijro** [comment]
Just pushed!
