### ISSUE TITLE
r.content to Bytes or r.raw is needed for binaries.

### ISSUE THREAD

**Issue by Aciid** [daijro/hrequests#24]
Hi, I have tried downloading images, the request.content is not raw bytes? 
I've tried mangling the r.content to .encode('utf-8') / decoding(uncode-escapes), but to no avail. The response is always some weird mix of encoded and escaped string and bytes.
The Request class implementation is different from requests.Request() and does not support requests.Request.raw and r.content is not Bytes.

Is there any workaround? Cheers

Sample code:
```
url = f"https://upload.wikimedia.org/wikipedia/commons/5/59/Shrine_of_Rememberance_%2811884180023%29.jpg"
filePath = os.path.join("tmp", f"image.jpg")
while True:
    r = hrequests.request("GET", url)
    if r.status_code != 403:
        data = r.content.encode('utf-8') 
        with open(filePath, "wb") as f:
            f.write(data)
        break
```
Output from r:
![snip](https://github.com/daijro/hrequests/assets/703382/4b309c13-55e0-4736-95e1-6bc9a273e450)

Resulting binary r.content.encode('utf-8'):
![image](https://github.com/daijro/hrequests/assets/703382/fb974d94-8c40-4179-a84b-e8c874f404ff)

**Comment by danielcrane** [comment]
A bit late but are you still looking for a workaround for this?

**Comment by daijro** [comment]
Should be fixed in the latest beta. Related to #31 ([see here](https://github.com/daijro/hrequests/issues/31#issuecomment-1925725738)).
