### ISSUE TITLE
No Binaries for M1 Macs

### ISSUE THREAD

**Issue by barneygovan** [daijro/hrequests#36]
Installing version 0.8.0 or above doesn't work on M1 (or presumably M2) Macs, due to the missing binaries.

```
/lib/python3.10/site-packages/hrequests/cffi.py", line 98, in download_library
    raise IOError('Could not find a matching binary for your system.')
OSError: Could not find a matching binary for your system.
```

Temporary workaround is to install: 
```
pip install -U "hrequests[all]<0.8.0"
```

Are there plans to include these binaries? Or perhaps some instructions on how to compile them myself?

**Comment by Noah-Law** [comment]
Same issue here.

**Comment by daijro** [comment]
I accidentally left `darwin-10.12` in the binary file names for the hrequests-cgo 2.1 release. It should work now 👍
