### ISSUE TITLE
How  i can use  Browser Automation?

### ISSUE THREAD

**Issue by Naimish1021** [daijro/hrequests#37]
> page =  hrequests.BrowserSession()

i have tried to use Browser Automation as you given in example but it is showing error like this : 
**AttributeError: module 'hrequests' has no attribute 'BrowserSession'**

and i also tried this example : 

> session = hrequests.Session(browser='chrome')
> resp = session.get('https://quotes.toscrape.com/page/1/')
> with resp.render(mock_human=True) as page:
>     print(page.text)

and it's also throwing error : **AttributeError: module 'hrequests' has no attribute 'browser'**

**Comment by daijro** [comment]
Hello,

It looks like you need to install hrequests with browser automation support.
Please run these commands:
```cmd
python -m pip install hrequests[all]
python -m hrequests install
```

I apologize if it wasn't clear. I'll add an error message with instructions by the next update 👍

**Comment by Naimish1021** [comment]
thanks for your answer.
i will check it and i would really like to work with it. :+1:
