### ISSUE TITLE
Potential Memory Leak in Proxied Session Responses

### ISSUE THREAD

**Issue by p4r4xor** [daijro/hrequests#47]
Hi daijro,

First, I want to thank you for this fantastic tool—it's been incredibly useful for my projects!

I've encountered a potential memory leak when rendering responses in a proxied session. Here’s a simple script that replicates the issue:

```
import hrequests

proxy = "http://proxy-url:port" 
url = "https://www.google.com/"
n = n

for iteration in range(n):
    with hrequests.Session() as session:
        session.proxy = proxy
        response = session.get(url, verify=True)
        rendered_response = response.render(mock_human=True)
        print(iteration, rendered_response.cookies)
        rendered_response.close()
```
I'm using Bloomberg's Memray to profile the script, and I've observed a significant memory increase over multiple iterations.

For n = 100, the memory profile looks like this:

![Screenshot from 2024-06-26 04-39-01](https://github.com/daijro/hrequests/assets/49688892/98f189b6-b8e5-4702-989b-1df5d1146708)

For n = 400, the memory profile shows a considerable increase:

![Screenshot from 2024-06-26 04-39-12](https://github.com/daijro/hrequests/assets/49688892/f94d9715-6bf3-4b48-96d0-7e113dfa6f88)

Is this behavior expected, or could it indicate a memory leak? Any insights would be greatly appreciated.
Open files can be checked by the command below.
```
lsof -U +c 15 | cut -f1 -d' ' | sort | uniq -c | sort -rn | head -6
```

Thank you!

### Environment:
OS: Ubuntu 22.04.4 LTS x86_64
Python version: 3.8.10
Python module versions:
```
hrequests: 0.8.2
rich: 13.7.1
aioprocessing: 2.0.1
click: 8.1.7
faust-cchardet: 2.1.19
selectolax: 0.3.21
orjson: 3.10.5
parse: 1.20.2
urllib3: 1.26.5
httpx: 0.27.0
gevent: 24.2.1
numpy: 1.21.5
geventhttpclient: 2.3.1
async-class: 0.5.0
pycryptodome: 3.20.0
playwright: 1.34.0
playwright-stealth: 1.0.6
greenlet: 2.0.2
pyee: 9.0.4
typing-extensions: 4.11.0
zope.event: 5.0
zope.interface: 6.3
brotli: 1.0.9
certifi: 2024.2.2
sniffio: 1.3.1
httpcore: 1.0.5
anyio: 4.4.0
idna: 3.3
h11: 0.14.0
pygments: 2.18.0
markdown-it-py: 3.0.0
mdurl: 0.1.2
exceptiongroup: 1.2.1
setuptools: 59.6.0
```

**Comment by daijro** [comment]
Thanks, In v0.9.0, hrequests no longer relies on a third party dependency to handle proxies  :+1:
