### ISSUE TITLE
Unable to Install hrequests[all]

### ISSUE THREAD

**Issue by Anish0612** [daijro/hrequests#59]
I am using Mac M1 I can't able to pip install -U hrequests[all]
When I try to run this command I got the Error:
zsh: no matches found: hrequests[all]

**Comment by josephvore** [comment]
Use quotes

**Comment by Anish0612** [comment]
Thanks but I am facing another problem while installing

Building wheels for collected packages: greenlet, gevent
  Building wheel for greenlet (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [173 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.macosx-11.0-arm64-cpython-312/greenlet
      copying src/greenlet/__init__.py -> build/lib.macosx-11.0-arm64-cpython-312/greenlet
      creating build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/__init__.py -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      creating build/lib.macosx-11.0-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_version.py -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_weakref.py -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_gc.py -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/leakcheck.py -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_generator.py -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_greenlet_trash.py -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_throw.py -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_tracing.py -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_cpp.py -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_contextvars.py -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_greenlet.py -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_extension_interface.py -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/__init__.py -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_generator_nested.py -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_stack_saved.py -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/test_leaks.py -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/tests
      running egg_info
      writing src/greenlet.egg-info/PKG-INFO
      writing dependency_links to src/greenlet.egg-info/dependency_links.txt
      writing requirements to src/greenlet.egg-info/requires.txt
      writing top-level names to src/greenlet.egg-info/top_level.txt
      reading manifest file 'src/greenlet.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files found matching 'benchmarks/*.json'
      no previously-included directories found matching 'docs/_build'
      warning: no files found matching '*.py' under directory 'appveyor'
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.pyd' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      warning: no previously-included files matching '.coverage' found anywhere in distribution
      adding license file 'LICENSE'
      adding license file 'LICENSE.PSF'
      adding license file 'AUTHORS'
      writing manifest file 'src/greenlet.egg-info/SOURCES.txt'
      copying src/greenlet/greenlet.cpp -> build/lib.macosx-11.0-arm64-cpython-312/greenlet
      copying src/greenlet/greenlet.h -> build/lib.macosx-11.0-arm64-cpython-312/greenlet
      copying src/greenlet/greenlet_allocator.hpp -> build/lib.macosx-11.0-arm64-cpython-312/greenlet
      copying src/greenlet/greenlet_compiler_compat.hpp -> build/lib.macosx-11.0-arm64-cpython-312/greenlet
      copying src/greenlet/greenlet_cpython_compat.hpp -> build/lib.macosx-11.0-arm64-cpython-312/greenlet
      copying src/greenlet/greenlet_exceptions.hpp -> build/lib.macosx-11.0-arm64-cpython-312/greenlet
      copying src/greenlet/greenlet_greenlet.hpp -> build/lib.macosx-11.0-arm64-cpython-312/greenlet
      copying src/greenlet/greenlet_internal.hpp -> build/lib.macosx-11.0-arm64-cpython-312/greenlet
      copying src/greenlet/greenlet_refs.hpp -> build/lib.macosx-11.0-arm64-cpython-312/greenlet
      copying src/greenlet/greenlet_slp_switch.hpp -> build/lib.macosx-11.0-arm64-cpython-312/greenlet
      copying src/greenlet/greenlet_thread_state.hpp -> build/lib.macosx-11.0-arm64-cpython-312/greenlet
      copying src/greenlet/greenlet_thread_state_dict_cleanup.hpp -> build/lib.macosx-11.0-arm64-cpython-312/greenlet
      copying src/greenlet/greenlet_thread_support.hpp -> build/lib.macosx-11.0-arm64-cpython-312/greenlet
      copying src/greenlet/slp_platformselect.h -> build/lib.macosx-11.0-arm64-cpython-312/greenlet
      copying src/greenlet/platform/setup_switch_x64_masm.cmd -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_aarch64_gcc.h -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_alpha_unix.h -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_amd64_unix.h -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_arm32_gcc.h -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_arm32_ios.h -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_arm64_masm.asm -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_arm64_masm.obj -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_arm64_msvc.h -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_csky_gcc.h -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_m68k_gcc.h -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_mips_unix.h -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_ppc64_aix.h -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_ppc64_linux.h -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_ppc_aix.h -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_ppc_linux.h -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_ppc_macosx.h -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_ppc_unix.h -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_riscv_unix.h -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_s390_unix.h -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_sparc_sun_gcc.h -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_x32_unix.h -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_x64_masm.asm -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_x64_masm.obj -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_x64_msvc.h -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_x86_msvc.h -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/platform/switch_x86_unix.h -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/platform
      copying src/greenlet/tests/_test_extension.c -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/tests
      copying src/greenlet/tests/_test_extension_cpp.cpp -> build/lib.macosx-11.0-arm64-cpython-312/greenlet/tests
      running build_ext
      building 'greenlet._greenlet' extension
      creating build/temp.macosx-11.0-arm64-cpython-312/src/greenlet
      clang++ -fno-strict-overflow -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /Users/anish/ls/include -arch arm64 -fPIC -O2 -isystem /Users/anish/ls/include -arch arm64 -I/Users/anish/ls/include/python3.12 -c src/greenlet/greenlet.cpp -o build/temp.macosx-11.0-arm64-cpython-312/src/greenlet/greenlet.o --std=gnu++11
      In file included from src/greenlet/greenlet.cpp:19:
      In file included from src/greenlet/greenlet_internal.hpp:20:
      src/greenlet/greenlet_greenlet.hpp:831:41: error: no member named 'use_tracing' in '_PyCFrame'
        831 |     this->use_tracing = tstate->cframe->use_tracing;
            |                         ~~~~~~~~~~~~~~  ^
      src/greenlet/greenlet_greenlet.hpp:834:37: error: no member named 'recursion_limit' in '_ts'; did you mean 'py_recursion_limit'?
        834 |     this->recursion_depth = tstate->recursion_limit - tstate->recursion_remaining;
            |                                     ^~~~~~~~~~~~~~~
            |                                     py_recursion_limit
      /Users/anish/ls/include/python3.12/cpython/pystate.h:148:9: note: 'py_recursion_limit' declared here
        148 |     int py_recursion_limit;
            |         ^
      In file included from src/greenlet/greenlet.cpp:19:
      In file included from src/greenlet/greenlet_internal.hpp:20:
      src/greenlet/greenlet_greenlet.hpp:834:63: error: no member named 'recursion_remaining' in '_ts'; did you mean 'c_recursion_remaining'?
        834 |     this->recursion_depth = tstate->recursion_limit - tstate->recursion_remaining;
            |                                                               ^~~~~~~~~~~~~~~~~~~
            |                                                               c_recursion_remaining
      /Users/anish/ls/include/python3.12/cpython/pystate.h:150:9: note: 'c_recursion_remaining' declared here
        150 |     int c_recursion_remaining;
            |         ^
      In file included from src/greenlet/greenlet.cpp:19:
      In file included from src/greenlet/greenlet_internal.hpp:20:
      src/greenlet/greenlet_greenlet.hpp:848:42: error: no member named 'trash_delete_nesting' in '_ts'
        848 |     this->trash_delete_nesting = tstate->trash_delete_nesting;
            |                                  ~~~~~~  ^
      src/greenlet/greenlet_greenlet.hpp:867:21: error: no member named 'use_tracing' in '_PyCFrame'
        867 |     tstate->cframe->use_tracing = this->use_tracing;
            |     ~~~~~~~~~~~~~~  ^
      src/greenlet/greenlet_greenlet.hpp:870:13: error: no member named 'recursion_remaining' in '_ts'; did you mean 'c_recursion_remaining'?
        870 |     tstate->recursion_remaining = tstate->recursion_limit - this->recursion_depth;
            |             ^~~~~~~~~~~~~~~~~~~
            |             c_recursion_remaining
      /Users/anish/ls/include/python3.12/cpython/pystate.h:150:9: note: 'c_recursion_remaining' declared here
        150 |     int c_recursion_remaining;
            |         ^
      In file included from src/greenlet/greenlet.cpp:19:
      In file included from src/greenlet/greenlet_internal.hpp:20:
      src/greenlet/greenlet_greenlet.hpp:870:43: error: no member named 'recursion_limit' in '_ts'; did you mean 'py_recursion_limit'?
        870 |     tstate->recursion_remaining = tstate->recursion_limit - this->recursion_depth;
            |                                           ^~~~~~~~~~~~~~~
            |                                           py_recursion_limit
      /Users/anish/ls/include/python3.12/cpython/pystate.h:148:9: note: 'py_recursion_limit' declared here
        148 |     int py_recursion_limit;
            |         ^
      In file included from src/greenlet/greenlet.cpp:19:
      In file included from src/greenlet/greenlet_internal.hpp:20:
      src/greenlet/greenlet_greenlet.hpp:881:13: error: no member named 'trash_delete_nesting' in '_ts'
        881 |     tstate->trash_delete_nesting = this->trash_delete_nesting;
            |     ~~~~~~  ^
      src/greenlet/greenlet_greenlet.hpp:891:48: error: no member named 'use_tracing' in '_PyCFrame'
        891 |     this->use_tracing = origin_tstate->cframe->use_tracing;
            |                         ~~~~~~~~~~~~~~~~~~~~~  ^
      src/greenlet/greenlet_greenlet.hpp:899:37: error: no member named 'recursion_limit' in '_ts'; did you mean 'py_recursion_limit'?
        899 |     this->recursion_depth = tstate->recursion_limit - tstate->recursion_remaining;
            |                                     ^~~~~~~~~~~~~~~
            |                                     py_recursion_limit
      /Users/anish/ls/include/python3.12/cpython/pystate.h:148:9: note: 'py_recursion_limit' declared here
        148 |     int py_recursion_limit;
            |         ^
      In file included from src/greenlet/greenlet.cpp:19:
      In file included from src/greenlet/greenlet_internal.hpp:20:
      src/greenlet/greenlet_greenlet.hpp:899:63: error: no member named 'recursion_remaining' in '_ts'; did you mean 'c_recursion_remaining'?
        899 |     this->recursion_depth = tstate->recursion_limit - tstate->recursion_remaining;
            |                                                               ^~~~~~~~~~~~~~~~~~~
            |                                                               c_recursion_remaining
      /Users/anish/ls/include/python3.12/cpython/pystate.h:150:9: note: 'c_recursion_remaining' declared here
        150 |     int c_recursion_remaining;
            |         ^
      In file included from src/greenlet/greenlet.cpp:21:
      In file included from src/greenlet/greenlet_slp_switch.hpp:82:
      In file included from src/greenlet/slp_platformselect.h:53:
      src/greenlet/platform/switch_aarch64_gcc.h:71:51: warning: value size does not match register size specified by the constraint and modifier [-Wasm-operand-widths]
         71 |            __asm__ volatile ("mov %0, #0" : "=r" (err));
            |                                                   ^
      src/greenlet/platform/switch_aarch64_gcc.h:71:35: note: use constraint modifier "w"
         71 |            __asm__ volatile ("mov %0, #0" : "=r" (err));
            |                                   ^~
            |                                   %w0
      src/greenlet/greenlet.cpp:3095:36: error: no member named 'trash_delete_nesting' in '_ts'
       3095 |     return PyLong_FromLong(tstate->trash_delete_nesting);
            |                            ~~~~~~  ^
      1 warning and 12 errors generated.
      error: command '/usr/bin/clang++' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for greenlet
  Running setup.py clean for greenlet
  Building wheel for gevent (pyproject.toml) ... done
  Created wheel for gevent: filename=gevent-22.10.2-cp312-cp312-macosx_11_0_arm64.whl size=1692568 sha256=260872b9c98152afbb6eb7e06661209f0839336f572ebd793eb45b3e9eff566c
  Stored in directory: /Users/anish/Library/Caches/pip/wheels/49/47/a4/d447aaeeb50c2aa56e8cf5ab39ccc9f7e52ce02d288971ba96
Successfully built gevent
Failed to build greenlet
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (greenlet)

**Comment by daijro** [comment]
Fixed in v0.9.0 :+1:
