### ISSUE TITLE
Contact with me

### ISSUE THREAD

**Issue by MaxAndolini** [daijro/hrequests#6]
I'm sorry to write here, but can you contact me about something on discord @max_andolini

**Comment by daijro** [comment]
Hello, could you email me?
You can reach me at daijro.dev@gmail.com. Thanks

**Comment by MaxAndolini** [comment]
> Hello, could you email me? You can reach me at [daijro.dev@gmail.com](mailto:daijro.dev@gmail.com). Thanks

Can you check your e-mails?

**Comment by daijro** [comment]
Sorry, your email was marked as spam. I was able to fix your issue.

**Comment by MaxAndolini** [comment]
> Sorry, your email was marked as spam.
> 
> Just responded, I was able to fix your issue.

Can you check your e-mails again?
