### ISSUE TITLE
I can't install the new version

### ISSUE THREAD

**Issue by tufkubie** [daijro/hrequests#64]
I can't install the new version. When I try to install it as in the documentation, version 0.8.2 is installed. I also get an error when I try to install it manually.

I have tried Python 3.12, 3.11, 3.10, 3.9 but without success.

> Collecting hrequests==0.9.0b0 (from hrequests[all]==0.9.0b0)
>   Using cached hrequests-0.9.0b0-py3-none-any.whl.metadata (48 kB)
> Collecting aioprocessing (from hrequests==0.9.0b0->hrequests[all]==0.9.0b0)
>   Using cached aioprocessing-2.0.1-py3-none-any.whl.metadata (7.6 kB)
> Collecting async-class (from hrequests==0.9.0b0->hrequests[all]==0.9.0b0)
>   Using cached async-class-0.5.0.tar.gz (5.4 kB)
>   Preparing metadata (setup.py) ... done
> Collecting browserforge (from hrequests==0.9.0b0->hrequests[all]==0.9.0b0)
>   Using cached browserforge-1.1.2-py3-none-any.whl.metadata (28 kB)
> Collecting event (from hrequests==0.9.0b0->hrequests[all]==0.9.0b0)
>   Using cached event-0.4.3.zip (56 kB)
>   Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
> 
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [7 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "/tmp/pip-install-3xrfmngw/event_7d210b24006949aa8d68fc7723eb1c6c/setup.py", line 20
>           print 'found libevent build directory', best
>                 ^
>       SyntaxError: Missing parentheses in call to 'print'. Did you mean print('found libevent build directory', best)?
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.

**Comment by Nongzhsh** [comment]
> I can't install the new version. When I try to install it as in the documentation, version 0.8.2 is installed. I also get an error when I try to install it manually.
> 
> I have tried Python 3.12, 3.11, 3.10, 3.9 but without success.
> 
> > Collecting hrequests==0.9.0b0 (from hrequests[all]==0.9.0b0)
> > Using cached hrequests-0.9.0b0-py3-none-any.whl.metadata (48 kB)
> > Collecting aioprocessing (from hrequests==0.9.0b0->hrequests[all]==0.9.0b0)
> > Using cached aioprocessing-2.0.1-py3-none-any.whl.metadata (7.6 kB)
> > Collecting async-class (from hrequests==0.9.0b0->hrequests[all]==0.9.0b0)
> > Using cached async-class-0.5.0.tar.gz (5.4 kB)
> > Preparing metadata (setup.py) ... done
> > Collecting browserforge (from hrequests==0.9.0b0->hrequests[all]==0.9.0b0)
> > Using cached browserforge-1.1.2-py3-none-any.whl.metadata (28 kB)
> > Collecting event (from hrequests==0.9.0b0->hrequests[all]==0.9.0b0)
> > Using cached event-0.4.3.zip (56 kB)
> > Preparing metadata (setup.py) ... error
> > error: subprocess-exited-with-error
> > × python setup.py egg_info did not run successfully.
> > │ exit code: 1
> > ╰─> [7 lines of output]
> > Traceback (most recent call last):
> > File "", line 2, in 
> > File "", line 34, in 
> > File "/tmp/pip-install-3xrfmngw/event_7d210b24006949aa8d68fc7723eb1c6c/setup.py", line 20
> > print 'found libevent build directory', best
> > ^
> > SyntaxError: Missing parentheses in call to 'print'. Did you mean print('found libevent build directory', best)?
> > [end of output]
> > note: This error originates from a subprocess, and is likely not a problem with pip.
> > error: metadata-generation-failed
> > × Encountered error while generating package metadata.
> > ╰─> See above for output.
> > note: This is an issue with the package mentioned above, not pip.
> > hint: See above for details.

I have the same error. 😅

**Comment by daijro** [comment]
Fixed in v0.9.0b2 :+1:
