### ISSUE TITLE
zStandard zstd issue

### ISSUE THREAD

**Issue by libexpand** [daijro/hrequests#74]
By default the `get` headers are `{'Accept-Encoding': 'gzip, deflate, br, zstd'}`. A webpage that returns as a zStandard (zstd), fails to decode.

`resp.headers['Content-Encoding']` returns `zstd`
`resp.encoding` returns `None`
`resp.text` returns:
```
...
    resp.text
    ^^^^^^^^^
  File "/home/vm/.venv/lib/python3.12/site-packages/hrequests/response.py", line 178, in text
    return self.raw if type(self.raw) is str else self.raw.decode(self.encoding)
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: decode() argument 'encoding' must be str, not None
```

**Comment by daijro** [comment]
Fixed in v0.9.2 :+1:
